### ISSUE TITLE
On Solaris, The DATA constant succeeds in locking the file DATA came from FAILED

### ISSUE THREAD

**Issue by ngoto** [ruby/mspec#12]
```
$ MSPECOPT="--verbose" make test-rubyspec
(snip)
/XXXXX/trunk-51741/spec/rubyspec/language/predefined/data_spec.rb                                           /XXXXX/trunk-51741/spec/rubyspec/language/predefined/fixtures/data_flock.rb:1:in `flock': Bad file number @ rb_file_flock - /XXXXX/trunk-51741/spec/rubyspec/language/predefined/fixtures/data_flock.rb (Errno::EBADF)
        from /XXXXX/trunk-51741/spec/rubyspec/language/predefined/fixtures/data_flock.rb:1:in `<main>'
F
(snip)

1)
The DATA constant succeeds in locking the file DATA came from FAILED
Expected ""
 to equal "0"

/XXXXX/trunk-51741/spec/rubyspec/language/predefined/data_spec.rb:31:in `block (3 levels) in <top (required)>'
/XXXXX/trunk-51741/spec/rubyspec/language/predefined/data_spec.rb:3:in `<top (required)>'
(snip)
```

On Solaris, write access is needed to lock a file.
This is well known difference of behavior between Solaris and Linux.
Plese see previous discussions in http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/291535

**Comment by ngoto** [comment]
In addition, see https://rails.lighthouseapp.com/projects/8994/tickets/6662-fileflock-cant-lock-read-only-file-for-exclusive-access

**Comment by eregon** [comment]
Can you provide a pull request to show what would be the changes?
If common behavior can be found easily, then that's best otherwise
a `platform_is_not :solaris do` guard should be used where appropriate, with a corresponding `platform_is :solaris do` if that makes sense.

**Comment by ngoto** [comment]
moved to the above issues in ruby/rubyspec
