### ISSUE TITLE
Support mruby

### ISSUE THREAD

**Issue by ksss** [ruby/mspec#16]
Dear all.

I'm working on project what run specs ruby/spec on mruby.

https://github.com/ksss/mruby-spec

I have some feedbacks to run specs ruby/spec on mruby.

1. `"str" "str"` is SyntaxError
1. mruby doesn't have `defined?`
1. `require 'rbconfig'`
1. `require 'pp'`
1. `require 'iconv'`
1. Need some patch

See also [mruby-spec](https://github.com/ksss/mruby-spec).

---

I can send a PR from my forked [mspec](https://github.com/ksss/mspec/tree/mruby) to here.

This PR can fix **1.** and **2.**
But **3.** ~ **6.** is not.

**3.** is using as hooks of **6.** because `require 'rbconfig'` is called by beginning part.

https://github.com/ruby/mspec/blob/8c048530d53879c825ffb4588f65289e22e1ea77/lib/mspec/guards/guard.rb#L4

**4.** can avoid to use [mruby-pp](https://github.com/kou/mruby-pp) and make a empty file for require.

**5.** problem is still undecided. because I don't encount this issue. But this issue will be able to cope by [mruby-iconv](https://github.com/mattn/mruby-iconv)

**6.** I have no idea. I can add some patch to [here](https://github.com/ksss/mruby-spec/blob/master/todo/rbconfig.rb). But I think it will become issue of each library if we want to resolve, probably.

**Comment by eregon** [comment]
Sounds great, thanks for the investigation!
The simpler mspec is, the better.
So if we can simplify without removing functionality, or gradually degrading to support more rubies, it's all good!

**Comment by eregon** [comment]
3: It seems we could require `rbconfig` later, and fallback gracefully to RUBY_PLATFORM otherwise.
4: This should be made optional, probably with a warning, and just call `inspect` instead of 
`pretty_inspect`.
5: that sounds like old code we could remove.
6: I used iij/mruby which supported some of these. Is it acceptable to use some mruby-gems to run ruby/spec?

**Comment by ksss** [comment]
3: In that case, mruby-spec needs other hook point to read some patches. (of cause, mruby-spec should remove all patches)

4:,5: Sounds good.

6: Yes, it is. iij/mruby can run ruby/spec, probably.

[iij/mruby "s1" branch](https://github.com/iij/mruby/tree/s1) include some mrbgems.

But it doesn't have some of the features.
So after all, It cannot remove all patches.

These are minimum requirement to run ruby/mspec on mruby if use mrbgems whether mruby/mruby or iij/mruby.

**RbConfig::CONFIG["RUBY_INSTALL_NAME"] || RbConfig::CONFIG["ruby_install_name"]**: https://github.com/ruby/mspec/blob/d1f3c0b5996bb0a8420cae9b6604bfff98be64fe/lib/mspec/helpers/ruby_exe.rb#L101

**RbConfig::CONFIG['bindir']**: https://github.com/ruby/mspec/blob/d1f3c0b5996bb0a8420cae9b6604bfff98be64fe/lib/mspec/helpers/ruby_exe.rb#L103

**Dir.[]**: https://github.com/ruby/mspec/blob/abc90e837514830a6c72aff5a99a6f3f4fcbb400/lib/mspec/utils/script.rb#L180
I avoid this issue to use https://github.com/gromnitsky/mruby-dir-glob

**RbConfig::CONFIG['host_os'] || RUBY_PLATFORM**: https://github.com/ruby/mspec/blob/abc90e837514830a6c72aff5a99a6f3f4fcbb400/lib/mspec/guards/guard.rb#L170

**RUBY_PATCHLEVEL**: https://github.com/ruby/mspec/blob/abc90e837514830a6c72aff5a99a6f3f4fcbb400/lib/mspec/guards/guard.rb#L65
mruby doesn't have patch level.

**File.executable?**: https://github.com/ruby/mspec/blob/d1f3c0b5996bb0a8420cae9b6604bfff98be64fe/lib/mspec/helpers/ruby_exe.rb#L111
I avoid this issue to use https://github.com/ksss/mruby-file-stat

**Comment by ksss** [comment]
I forgot to write.
mruby's integer range changeable 16, 32 or 64 bit.
`SpecVersion#<=>` needs `MRB_INT64` configuration in [mruby/mrbconf.h](https://github.com/mruby/mruby/blob/08a1dd2ac89333bd928a3300f712d1a7fb57e8ff/include/mrbconf.h#L18).
Because `SpecVersion#to_i` is too big to use on 32 bit(mruby's default).

https://github.com/ruby/mspec/blob/d1f3c0b5996bb0a8420cae9b6604bfff98be64fe/lib/mspec/utils/version.rb#L35

On 32 bit,

```
"10105170000".to_i
# ArgumentError string (10105170000) too big for integer
```

I avoid this issue to use MRB_INT64. 

https://github.com/ksss/mruby-spec/blob/851a9ec2fca5e2ae9e4e8657ce12b73f17325688/Makefile#L13

I want to use mruby's default integer(32bit) if possible.

**Comment by eregon** [comment]
I addressed `iconv`, `pp` and `defined?` issues on master, these should no longer be a problem.

**Comment by eregon** [comment]
f86fda400e18aa69c001c9db2967c81d93fcda4f should fix the integer out of range issue.

**Comment by eregon** [comment]
> 3: In that case, mruby-spec needs other hook point to read some patches. (of cause, mruby-spec should remove all patches)

The mspec config file (by default `default.mspec` in ruby/spec) could serve for this but unfortunately I think it's required after mspec is loaded, so it does not work for this use case.

**Comment by eregon** [comment]
`RbConfig::CONFIG["RUBY_INSTALL_NAME"] || RbConfig::CONFIG["ruby_install_name"]:` and
`RbConfig::CONFIG['bindir']:`
 are not needed if `:target` is set in the mspec config file.

**Comment by eregon** [comment]
> `Dir.[]:`

It seems used only in `return Dir["#{expanded}/**/*_spec.rb"].sort`, which we could try to implement with some directory listing method like Dir.entries or Dir.foreach, bnut `mruby` does not even define `Dir`.

One possibility might be to use another Ruby to start the mspec script, and then execute with mruby the specs:

```bash
standard_ruby path/to/mspec/bin/mspec path/to/some_spec.rb -t bin/mruby
```

**Comment by eregon** [comment]
See https://github.com/ksss/mruby-spec/pull/1

**Comment by ksss** [comment]
Really really great. I'm so excited!

**Comment by eregon** [comment]
@ksss Anything else we could do to help mruby run mspec for ruby/spec?
Otherwise let's close this and if anything can be improved, please open a new issue :)

**Comment by ksss** [comment]
Yes, Thank you for your many kindness.
I'll close this issue.
