### ISSUE TITLE
cleanup branches

### ISSUE THREAD

**Issue by hsbt** [ruby/mspec#3]
we have needless branches without master. I will delete these branches after pass rubyci

**Comment by eregon** [comment]
I removed already merged branches such as delete_temp_dir_only_by_main_process and ruby2.
`old_ruby` was a synonym of `ruby` I created but I removed it as I think it is better to remove the `ruby` branch and only keep `master`.
`master` is rubyspec master branch with our commits on top, which is cleaner than the `ruby` branch as it does not have conflicting commits with rubyspec/master. But therefore as it is a rebase it is not a fast forward from the `ruby` branch. (Given the few commits I would think it is not a big problem)

`balance_should_and_matchers` is inherited from upstream, so we can probably remove it as well.

**Comment by eregon** [comment]
I intend to do a force push once https://github.com/rubyspec/mspec/pull/61 is merged (in a couple hours normally) if that is OK, so to stay on top of rubyspec/mspec.
In the future we might need to do proper merges with rubyspec/mspec but right now is a good time to avoid it I think.

**Comment by eregon** [comment]
I rebased on top of the commit merged to rubyspec/master for our master branch.

**Comment by eregon** [comment]
Can we remove the `ruby` branch from both rubyspec and mspec now?

**Comment by eregon** [comment]
@hsbt ping, is it OK to remove the `ruby` branches?

**Comment by hsbt** [comment]
Sorry. It's ok!

**Comment by eregon** [comment]
Done!
