### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by eregon** [ruby/mspec#4]
I am thinking to only keep one config file named ruby.mspec since they are currently all identical.
And then specify `--config ruby.mspec` to mspec.
What do you think?

**Comment by eregon** [comment]
This is actually more of a rubyspec change, but let's discuss here anyway.

**Comment by hsbt** [comment]
@eregon I agreed your suggestion. ```ruby.mspec``` is ok.

**Comment by eregon** [comment]
fixed by https://github.com/ruby/rubyspec/commit/7a909e925c1baa9c700bd44af9241aef6e596714.
Please update other sources to always specify the config file explicitly:
```
mspec --config path/to/rubyspec/ruby.mspec ...
```

**Comment by eregon** [comment]
This was changed again so `default.mspec` is good enough alone for MRI and no option needs to be passed if executing specs in the rubyspec directory.
