### ISSUE TITLE
Error: -e:1: `$(' is not allowed as a global variable name on OSs whose /bin/sh is not bash.

### ISSUE THREAD

**Issue by ngoto** [ruby/mspec#9]
On Solaris 10, the following error frequently occurs.

```
  -e:1: `$(' is not allowed as a global variable name
```

This error occurs in the ruby_cmd() method.
In lib/mspec/helpers/ruby_exe.rb line 152,

```
        body = %Q!-e "$(cat <<'#{heredoc_separator}'\n#{code}\n#{heredoc_separator}\n)"!
```

In the line, $() which should be interpreted by the system's shell is used.
However, on Solaris, because /bin/sh is traditional /bin/sh, $() can not be interpreted.
I think $() is a bash extension, and I think the error can occurr other OSs whose /bin/sh is not bash.

**Comment by nobu** [comment]
`$()` is now [POSIX standard](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_03),
but may not be supported on some systems.

**Comment by kachick** [comment]
@nobu Thank you!
@ngoto Sorry... I didn't know the /bin/sh in Solaris. :bow:  https://github.com/rubyspec/mspec/pull/48
